export const FETCHING_LOCATION_BY_CITY = "FETCHING_LOCATION_BY_CITY";
export const FETCH_LOCATION_BY_CITY_SUCCESS = "FETCH_LOCATION_BY_CITY_SUCCESS";
export const FETCH_LOCATION_BY_CITY_FAILED = "FETCH_LOCATION_BY_CITY_FAILED";
export const SET_EMPTY_LOCATION = "SET_EMPTY_LOCATION";
export const RESET_INIT_STATE = "RESET_INIT_STATE";

export const FETCHING_LOCATION_BY_WOEID = "FETCHING_LOCATION_BY_WOEID";
export const FETCH_LOCATION_BY_WOEID_SUCCESS =
  "FETCH_LOCATION_BY_WOEID_SUCCESS";
export const FETCH_LOCATION_BY_WOEID_FAILED = "FETCH_LOCATION_BY_WOEID_FAILED";
